"""First-run setup must validate before replacing any tracked template files."""

from __future__ import annotations

import shutil
from contextlib import nullcontext
from pathlib import Path

import pytest
from scripts import bootstrap as setup

from tests.copier_helpers import git


@pytest.fixture
def target(tmp_path):
    repo = tmp_path / "target"
    (repo / ".github").mkdir(parents=True)
    (repo / ".github/.template-pending").write_text("")
    (repo / "README.md").write_text("original template\n")
    (repo / ".gitignore").write_text(".env\n.venv/\nignored.txt\n")
    git(repo, "init", "-q", "-b", "main")
    git(repo, "add", "-A")
    git(repo, "commit", "-qm", "test: initial template")
    return repo


@pytest.fixture
def fake_renderer(monkeypatch):
    calls = []

    def copy(source, destination, **kwargs):
        calls.append((source, kwargs))
        destination.mkdir()
        (destination / "README.md").write_text("generated project\n")
        (destination / ".gitignore").write_text(".env\n.venv/\nignored.txt\n")
        (destination / "src").mkdir()
        (destination / "src/app.py").write_text("# generated\n")

    def validate(destination):
        (destination / "uv.lock").write_text("generated by validation fixture\n")
        (destination / ".venv").mkdir()
        (destination / ".venv/cache").write_text("do not install\n")

    monkeypatch.setattr(setup, "run_copy", copy)
    monkeypatch.setattr(setup, "validate_project", validate)
    return calls


def test_setup_preserves_git_and_ignored_data(target, fake_renderer):
    head = git(target, "rev-parse", "HEAD")
    (target / ".env").write_text("local settings\n")
    assert setup.bootstrap(target, repository="acme/weather-service", description="Weather tools")
    assert (target / "README.md").read_text() == "generated project\n"
    assert (target / ".env").read_text() == "local settings\n"
    assert (target / "uv.lock").is_file()
    assert not (target / ".venv").exists()
    assert not (target / ".github/.template-pending").exists()
    assert git(target, "rev-parse", "HEAD") == head
    assert fake_renderer[0][0] == "."
    assert fake_renderer[0][1]["vcs_ref"] == head
    assert fake_renderer[0][1]["data"]["description"] == "Weather tools"
    assert not setup.bootstrap(target, repository="acme/weather-service")
    assert len(fake_renderer) == 1


@pytest.mark.parametrize("change", ["tracked", "untracked", "staged"])
def test_dirty_target_is_rejected(target, fake_renderer, change):
    filename = "README.md" if change == "tracked" else "new.txt"
    (target / filename).write_text("local change\n")
    if change == "staged":
        git(target, "add", filename)
    with pytest.raises(ValueError, match="clean"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert not fake_renderer
    assert (target / filename).read_text() == "local change\n"


@pytest.mark.parametrize("flag", ["--assume-unchanged", "--skip-worktree"])
def test_hidden_tracked_edits_are_rejected(target, fake_renderer, flag):
    git(target, "update-index", flag, "README.md")
    (target / "README.md").write_text("hidden user change\n")
    assert git(target, "status", "--porcelain") == ""
    with pytest.raises(ValueError, match="index flags"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert not fake_renderer
    assert (target / "README.md").read_text() == "hidden user change\n"


@pytest.mark.parametrize("repository", ["justmumu/python-dev-template", "missing-owner", "too/many/slashes"])
def test_wrong_repository_is_rejected(target, fake_renderer, repository):
    with pytest.raises(ValueError):
        setup.bootstrap(target, repository=repository)
    assert not fake_renderer


def test_original_origin_is_rejected(target, fake_renderer):
    git(target, "remote", "add", "origin", f"https://github.com/{setup.TEMPLATE_REPOSITORY}.git")
    with pytest.raises(ValueError, match="original template"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert not fake_renderer


@pytest.mark.parametrize("phase", ["run_copy", "validate_project"])
def test_failure_before_install_leaves_target_untouched(target, fake_renderer, monkeypatch, phase):
    def fail(*args, **kwargs):
        raise RuntimeError("injected validation failure")

    monkeypatch.setattr(setup, phase, fail)
    with pytest.raises(RuntimeError, match="injected"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert git(target, "status", "--porcelain") == ""
    assert (target / ".github/.template-pending").exists()


def test_ignored_output_collision_is_rejected(target, fake_renderer, monkeypatch):
    original_copy = setup.run_copy

    def render(*args, **kwargs):
        original_copy(*args, **kwargs)
        (args[1] / "ignored.txt").write_text("generated\n")

    monkeypatch.setattr(setup, "run_copy", render)
    (target / "ignored.txt").write_text("personal\n")
    with pytest.raises(ValueError, match="collision"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert (target / "ignored.txt").read_text() == "personal\n"
    assert git(target, "status", "--porcelain") == ""


def test_symlink_ancestor_cannot_escape_target(target, fake_renderer, tmp_path):
    outside = tmp_path / "outside"
    outside.mkdir()
    (target / "src").symlink_to(outside, target_is_directory=True)
    git(target, "add", "src")
    git(target, "commit", "-qm", "test: symlink fixture")
    with pytest.raises(ValueError, match="symlink"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert not list(outside.iterdir())


def test_install_io_failure_restores_original_files(target, fake_renderer, monkeypatch):
    original_copy = shutil.copy2
    failed = False

    def fail_once(source, destination, *args, **kwargs):
        nonlocal failed
        if Path(destination) == target / "src/app.py" and not failed:
            failed = True
            raise OSError("injected disk failure")
        return original_copy(source, destination, *args, **kwargs)

    monkeypatch.setattr(shutil, "copy2", fail_once)
    with pytest.raises(OSError, match="injected"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert failed
    assert git(target, "status", "--porcelain") == ""
    assert (target / "README.md").read_text() == "original template\n"


def test_failed_restore_preserves_recovery_backup(target, fake_renderer, monkeypatch):
    original_copy = shutil.copy2
    backup = None

    def fail_install_and_restore(source, destination, *args, **kwargs):
        nonlocal backup
        source, destination = Path(source), Path(destination)
        if destination == target / "src/app.py":
            raise OSError("injected install failure")
        if "backup" in source.parts and destination.is_relative_to(target):
            backup = next(parent for parent in source.parents if parent.name == "backup")
            raise OSError("injected restore failure")
        return original_copy(source, destination, *args, **kwargs)

    monkeypatch.setattr(shutil, "copy2", fail_install_and_restore)
    with pytest.raises(OSError, match="backup"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert backup is not None
    assert (backup / "README.md").read_text() == "original template\n"
    assert (backup / ".github/.template-pending").is_file()
    shutil.rmtree(backup.parent)


def test_concurrent_edit_is_preserved(target, fake_renderer, monkeypatch):
    def validate(destination):
        (destination / "uv.lock").write_text("fixture\n")
        (target / "README.md").write_text("concurrent user change\n")

    monkeypatch.setattr(setup, "validate_project", validate)
    with pytest.raises(ValueError, match="clean"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert (target / "README.md").read_text() == "concurrent user change\n"


def test_head_change_during_validation_is_rejected(target, fake_renderer, monkeypatch):
    def validate(destination):
        (destination / "uv.lock").write_text("fixture\n")
        (target / "README.md").write_text("committed while validation ran\n")
        git(target, "add", "README.md")
        git(target, "commit", "-qm", "test: concurrent commit")

    monkeypatch.setattr(setup, "validate_project", validate)
    with pytest.raises(ValueError, match="HEAD changed"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert (target / "README.md").read_text() == "committed while validation ran\n"


def test_generated_symlinks_are_rejected(target, fake_renderer, monkeypatch):
    original_copy = setup.run_copy

    def render(*args, **kwargs):
        original_copy(*args, **kwargs)
        (args[1] / "link").symlink_to("README.md")

    monkeypatch.setattr(setup, "run_copy", render)
    with pytest.raises(ValueError, match="symlinks"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert git(target, "status", "--porcelain") == ""


@pytest.mark.parametrize("existing", [True, False])
def test_workflow_writes_that_github_token_cannot_push_are_rejected(target, fake_renderer, monkeypatch, existing):
    if existing:
        (target / ".github/workflows").mkdir()
        (target / ".github/workflows/ci.yml").write_text("original workflow\n")
        git(target, "add", "-A")
        git(target, "commit", "-qm", "test: original workflow")
    original_copy = setup.run_copy

    def render(*args, **kwargs):
        original_copy(*args, **kwargs)
        (args[1] / ".github/workflows").mkdir(parents=True)
        (args[1] / ".github/workflows/ci.yml").write_text("updated workflow\n")

    monkeypatch.setattr(setup, "run_copy", render)
    with pytest.raises(ValueError, match="workflow"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert git(target, "status", "--porcelain") == ""


def test_file_directory_collision_is_rejected(target, fake_renderer):
    (target / "src").write_text("existing tracked file\n")
    git(target, "add", "src")
    git(target, "commit", "-qm", "test: file collision")
    with pytest.raises(ValueError, match="collision"):
        setup.bootstrap(target, repository="acme/weather-service")
    assert (target / "src").read_text() == "existing tracked file\n"


def test_cli_passes_github_answers(target, fake_renderer, monkeypatch, capsys):
    monkeypatch.setenv("GITHUB_REPOSITORY", "acme/weather-service")
    monkeypatch.setenv("PROJECT_DESCRIPTION", "From GitHub description")
    setup.main(["--repo", str(target)])
    assert fake_renderer[0][1]["data"]["description"] == "From GitHub description"
    assert "generated and verified" in capsys.readouterr().out
    setup.main(["--repo", str(target)])
    assert "already complete" in capsys.readouterr().out


@pytest.mark.parametrize("build_docs", [True, False])
def test_validation_uses_make_without_node(target, monkeypatch, build_docs):
    commands = []

    def record(arguments, *, cwd=None):
        assert cwd == target
        commands.append(arguments)
        return ""

    monkeypatch.setattr(setup, "_run", record)
    setup.validate_project(target, build_docs=build_docs)
    expected = [
        ["git", "init", "-q", "-b", "main"],
        ["make", "install"],
        ["make", "format"],
        ["make", "check"],
    ]
    if build_docs:
        expected.append(["make", "docs-build"])
    expected.append(["uv", "build"])
    assert commands == expected


def test_nested_environment_keeps_python_selection_without_other_project_context(monkeypatch):
    monkeypatch.setenv("UV_PYTHON", "3.11")
    for name in ("VIRTUAL_ENV", "UV_PROJECT_ENVIRONMENT", "UV_PROJECT", "UV_WORKING_DIR", "PYTHONPATH", "GIT_DIR"):
        monkeypatch.setenv(name, "outer-project")
    environment = setup._environment()
    assert environment["UV_PYTHON"] == "3.11"
    assert all(
        name not in environment
        for name in ("VIRTUAL_ENV", "UV_PROJECT_ENVIRONMENT", "UV_PROJECT", "UV_WORKING_DIR", "PYTHONPATH", "GIT_DIR")
    )


@pytest.mark.parametrize("fails", [True, False])
def test_staging_directory_is_removed_after_ordinary_exit(fails):
    directories = []
    context = pytest.raises(ValueError, match="validation failed") if fails else nullcontext()
    with context, setup._staging_directory() as staging:
        directories.append(staging)
        assert staging.is_dir()
        if fails:
            raise ValueError("validation failed")
    assert len(directories) == 1
    assert not directories[0].exists()
